sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: T/yktkndzcvFvZyYev2cmEopq/HoHP92QYkmbfJuKxtkldNQw0Ii8tHd+FK2koZXPhLN5jLHCTt4/OeC138iGnJpUcKDlhs/ZV2hmWXXRJ7uemojdpQ+pAR9SoM3SqgNCsRNyUVej9PrRsNYxlJlfD7NlX4miiU1N305aDatXE4drlp7nO/VEGdJd8Y9QAdTZq0TgDJGYRSfe9U+iUH3gZMPG0fyH9PR6iBNmdBtf3rW3G+WClPoCIAxtzpkAeNqKjYFJ48g9maS4MHi0OMn/4YRX9CXpx05vERyQBj91ITJerYkTv747j1O6cmNohB3tisftSW/hbviRc3v8EIWGgw6wjQqJ7j57oUyt7sSDgZ7cisEnOc+wdPHz8b02uEMMxi6ub1x6MUHY9KGTY+6113vySySr9eEWQz+9Sl1+C2Sh59c4Rvao1D0yyU4NzxEqC3tYae6Q29p7bpj8mdK7IpCyKTH9awpMCz48mkhchGuXspXvOl7yRbhKz27V4kncwiymyoBni8SZ/qY7ZZljbTjAk/QcNARyokFx/IJelouv3j3iDp5lUcRAJPy9nrar3bQHf3pBaL5iEgf1f69NJSlJVqb3COzxjq6/w7QEBAeanrV4zZ4um4Doke+5dTuc+5mR4IYJ+QF188w29+QO7tLZGn/uQkywCTBiUGRScU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Letters-of-Marcus-Tullius-Cicero_2812
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy